apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app-child
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/nihal4014/gitops-react-app.git'
    targetRevision: HEAD
    path: react-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: react
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
